spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spp_lab9
    username: root
    password: 16111999m
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    root: debug